baseURL = "https://example.org"

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
[module.hugoVersion]
extended = false
min = "0.75.0"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/alpinejs"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/spruce"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/instantpage"

[build]
# Used by PurgeCSS
writeStats = true